In [22]:
import pandas as pd
import numpy as np
import pickle
from tensorflow import keras

model = keras.models.load_model('model.keras')

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [23]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Female',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [24]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Female,40,3,60000,2,1,1,50000

In [25]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,0,40,3,60000,2,1,1,50000

In [26]:
transformed_input = onehot_encoder_geo.transform(input_df)

In [27]:
input_df_final = pd.DataFrame(
    transformed_input,
    columns=onehot_encoder_geo.get_feature_names_out()
)

input_df_final

,geo__Geography_Germany,geo__Geography_Spain,remainder__CreditScore,remainder__Gender,remainder__Age,remainder__Tenure,remainder__Balance,remainder__NumOfProducts,remainder__HasCrCard,remainder__IsActiveMember,remainder__EstimatedSalary
0,0.0,0.0,600.0,0.0,40.0,3.0,60000.0,2.0,1.0,1.0,50000.0

In [28]:
input_scaled = scaler.transform(input_df_final)
input_scaled

c:\Users\MR\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

array([[-0.37796447, -0.57735027, -0.33932281, -0.77459667,  0.06884284,
        -0.45083482, -0.32830755,  0.        ,  0.37796447,  1.        ,
        -1.09686635]])

In [29]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

array([[0.8466498]], dtype=float32)

In [30]:
prediction_proba = prediction[0][0]
print("Prediction Probability:", prediction_proba)

if prediction_proba > 0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

Prediction Probability: 0.8466498
The customer is likely to churn